version: '3'
services:
  fastapi:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - redis
    environment:
      - DATABASE_URL=sqlite:///./sql_app.db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECRET_KEY=your-secret-key
      - ALGORITHM=HS256  
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

  redis:
    image: redis:latest